import streamlit as st
import oracledb
from sentence_transformers import SentenceTransformer

st.set_page_config(page_title="BARIŞ HANSU - Oracle 23ai Demo", layout="wide")
st.markdown("<h1 style='text-align: center; font-size: 3em;'>BARIŞ HANSU</h1>", unsafe_allow_html=True)
st.write("---")
st.title("🚀 Oracle 23ai: AI Vector Search Deneyimi")

@st.cache_resource
def get_model():
    return SentenceTransformer('all-MiniLM-L6-v2')

model = get_model()

st.sidebar.header("Sistem Durumu")
conn_status = st.sidebar.empty()

def get_connection():
    return oracledb.connect(user="system", password="Oracle_123_", dsn="localhost:1521/FREEPDB1")

if get_connection():
    conn_status.success("✅ Oracle 23ai Bağlı (Docker)")
else:
    conn_status.error("❌ Oracle Bağlantısı Yok")

# Ana Uygulama
tab1, tab2 = st.tabs(["🔍 Akıllı Arama", "📊 Veritabanı Yapısı"])

with tab1:
    query = st.text_input("Bir arama terimi girin (Anlamsal arama yapılacaktır):", 
                         placeholder="Örn: Uzayda geçen bir hayatta kalma hikayesi...")
    
    col1, col2 = st.columns([1, 4])
    search_limit = col1.slider("Sonuç Sayısı", 1, 5, 2)

    if st.button("AI Vector Search Çalıştır"):
        if query:
            with st.spinner("Vektörler hesaplanıyor ve Oracle içinde aranıyor..."):
                try:
                    conn = get_connection()
                    cursor = conn.cursor()
                    
                    query_vec_str = str(model.encode(query).tolist())
                    
                    sql = """
                        SELECT title, description, VECTOR_DISTANCE(embedding, TO_VECTOR(:vec)) as distance
                        FROM books
                        ORDER BY distance ASC
                        FETCH FIRST :lim ROWS ONLY
                    """
                    cursor.execute(sql, [query_vec_str, search_limit])
                    results = cursor.fetchall()
                    
                    if results:
                        for row in results:
                            st.info(f"**Kitap:** {row[0]}")
                            st.write(f"**Açıklama:** {row[1]}")
                            st.write(f"**Anlamsal Uzaklık Skoru:** {row[2]:.4f}")
                            st.progress(max(0.0, min(1.0, 1.0 - float(row[2])))) 
                    else:
                        st.warning("Veritabanında henüz veri yok. Yandaki sekmeden verileri yükleyin.")
                    
                    cursor.close()
                    conn.close()
                except Exception as e:
                    st.error(f"Hata: {e}")
        else:
            st.warning("Lütfen bir cümle girin.")

with tab2:
    st.subheader("Veritabanı Şeması ve Vektör Verisi")
    st.write("Bu buton, Oracle 23ai üzerinde 'BOOKS' tablosunu oluşturur ve 70 farklı veriyi AI ile vektörlere çevirip kaydeder.")
    
    if st.button("Örnek Veri Setini Yükle (Tabloyu Oluştur)"):
        with st.spinner("Tablolar oluşturuluyor ve 70 kayıt vektörleniyor... (Bu işlem yaklaşık 15-20 saniye sürebilir)"):
            try:
                conn = get_connection()
                cursor = conn.cursor()
                
                try:
                    cursor.execute("DROP TABLE books")
                except:
                    pass
                
                cursor.execute("""
                    CREATE TABLE books (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        title VARCHAR2(200),
                        description CLOB,
                        embedding VECTOR(384, FLOAT32)
                    ) TABLESPACE USERS
                """)
                
                kitaplar = [
                    ("Dune", "Çöl gezegeni Arrakis'te geçen, dev solucanlar ve baharat madenciliği üzerine kurulu epik bilimkurgu."),
                    ("Marslı", "Kızıl gezegende mahsur kalan bir astronotun zekasını kullanarak hayatta kalma mücadelesi."),
                    ("Sefiller", "19. yüzyıl Fransa'sında adaletsizlik, aşk ve kurtuluş arayışını anlatan tarihi bir dram."),
                    ("1984", "Büyük Birader'in her şeyi izlediği, özgür düşüncenin yasaklandığı distopik bir gelecek."),
                    ("Yüzüklerin Efendisi", "Karanlık lordun gücünü barındıran tek yüzüğü yok etmek için çıkılan tehlikeli fantastik yolculuk."),
                    ("Sapiens", "İnsan türünün taş devrinden günümüze kadar uzanan bilişsel ve kültürel evrimi."),
                    ("Suç ve Ceza", "Fakir bir öğrencinin işlediği cinayet sonrası yaşadığı psikolojik çöküş ve vicdan azabı."),
                    ("Zamanın Kısa Tarihi", "Evrenin doğuşu, kara delikler ve kuantum fiziği üzerine anlaşılır bir bilimsel eser."),
                    ("Yapay Zeka ve AutoML", "Makine öğrenimi modellerinin hiperparametre optimizasyonunu ve transfer öğrenmeyi otomatikleştiren sistemler."),
                    ("Otomobil Pazar Analizi", "İkinci el araç piyasasında alım-satım stratejileri, paket karşılaştırmaları ve fiyat analizleri."),
                    ("Hipertrofi ve Anatomi", "Sırt, ön kol ve arka kol kaslarını maksimum seviyede çalıştırmak için ağırlık antrenmanı prensipleri."),
                    ("Alt Seviye Programlama", "Bilgisayar mimarisinin temelleri ve Assembly dili ile donanıma en yakın kodlama teknikleri."),
                    ("İleri Seviye Java Mimarisi", "Büyük ölçekli sistemlerde nesne yönelimli programlama, Spring Boot ve veritabanı entegrasyonları."),
                    ("Simyacı", "Endülüs'ten Mısır piramitlerine hazine aramak için yola çıkan bir çobanın felsefi yolculuğu."),
                    ("Steve Jobs", "Teknoloji dünyasını değiştiren vizyoner bir liderin yenilikçi ürünler yaratma tutkusu."),
                    ("Sherlock Holmes", "Zeki bir dedektifin tümevarım yeteneğini kullanarak çözdüğü karmaşık cinayet vakaları."),
                    ("Da Vinci Şifresi", "Paris'te bir cinayetle başlayan, sanat eseri ve dini sembollerin içine gizlenmiş sırların çözümü."),
                    ("Gurur ve Önyargı", "18. yüzyıl İngiltere'sinde sosyal sınıf farklarına rağmen filizlenen klasik bir romantik hikaye."),
                    ("Türlerin Kökeni", "Doğal seçilim yoluyla evrim teorisini anlatan ve biyolojinin temelini atan çığır açıcı kitap."),
                    ("Saatleri Ayarlama Enstitüsü", "Doğu ile Batı kültürü arasında sıkışmış Türk toplumunun bürokrasi üzerinden hicvedilmesi."),
                    ("Kürk Mantolu Madonna", "İçine kapanık bir adamın Almanya'da bir resim sergisinde aşık olduğu kadınla yaşadığı duygusal anılar."),
                    ("Tutunamayanlar", "Toplumun kurallarına uyum sağlayamayan bireylerin iç dünyasını anlatan postmodern bir Türk romanı."),
                    ("Cesur Yeni Dünya", "İnsanların fabrikalarda üretildiği ve duyguların ilaçlarla bastırıldığı teknolojik bir distopya."),
                    ("Vakıf", "Çökmekte olan devasa bir galaktik imparatorluğun bilgi birikimini korumaya çalışan bilim insanları."),
                    ("Otostopçunun Galaksi Rehberi", "Dünyanın yok edilmesinin ardından uzayda otostop çekerek hayatta kalmaya çalışan bir adamın komik macerası."),
                    ("Kozmos", "Yıldızların oluşumundan galaksilerin yapısına kadar evrenin büyüklüğünü anlatan popüler bilim eseri."),
                    ("İki Şehrin Hikayesi", "Fransız Devrimi sırasında Paris ve Londra arasında geçen fedakarlık ve aşk temalı tarihi roman."),
                    ("Anna Karenina", "Rus aristokrasisi içinde mutsuz bir evlilik yaşayan bir kadının trajik ve tutkulu yasak aşkı."),
                    ("Beyaz Diş", "Vahşi doğada doğan yarı kurt bir köpeğin insanlarla olan zorlu ve merhametli ilişkisi."),
                    ("Şeker Portakalı", "Brezilya'da yoksul bir ailenin hayal gücü geniş ve yaramaz küçük çocuğunun duygu yüklü büyüme hikayesi."),
                    ("İnce Memed", "Çukurova'da zalim bir ağaya karşı başkaldıran ve adaleti arayan efsanevi bir eşkıyanın destanı."),
                    ("Satranç", "Gestapo tarafından hapsedilen bir adamın akıl sağlığını korumak için satranç tahtasında kurduğu dünya."),
                    ("Dönüşüm", "Bir sabah uyandığında kendini dev bir böceğe dönüşmüş olarak bulan adamın yabancılaşma hikayesi."),
                    ("Gülün Adı", "Ortaçağ'da bir manastırda meydana gelen gizemli cinayetleri soruşturan zeki bir rahibin hikayesi."),
                    ("Savaş ve Barış", "Napolyon'un Rusya'yı işgali sırasında beş farklı soylu ailenin iç içe geçmiş destansı yaşamları."),
                    ("Fareler ve İnsanlar", "Büyük Bunalım döneminde çiftliklerde çalışan iki zıt karakterli dostun trajik ve sarsıcı hikayesi."),
                    ("Yabancı", "Toplumsal normlara kayıtsız kalan ve absürt bir cinayet işleyen bir adamın varoluşsal bunalımı."),
                    ("Uçurtma Avcısı", "Afganistan'da savaşın gölgesinde büyüyen iki çocuğun dostluk, ihanet ve kefaret arayışını anlatan hikaye."),
                    ("Hayvan Çiftliği", "Çiftlikteki hayvanların isyan ederek kendi yönetimlerini kurmaları ve sonrasında yaşanan yozlaşma."),
                    ("İlahi Komedi", "Cehennem, Araf ve Cennet arasında yapılan, günah ve arınma temalı epik şiirsel yolculuk."),
                    ("Clean Code", "Yazılım mühendisliğinde okunabilir, bakımı kolay ve sürdürülebilir kod yazma prensipleri."),
                    ("Veri Yapıları ve Algoritmalar", "Büyük ölçekli sistemlerde verimli arama ve sıralama işlemleri için temel bilgisayar bilimleri kavramları."),
                    ("Tasarım Örüntüleri", "Yazılım tasarımında sık karşılaşılan sorunlara karşı geliştirilmiş, yeniden kullanılabilir çözüm şablonları."),
                    ("Elektrikli Araç Teknolojileri", "Modern otomobillerde batarya yönetimi, otonom sürüş ve elektrik motoru mimarileri."),
                    ("Performans Odaklı Beslenme", "Ağırlık antrenmanlarında kas gelişimini destekleyen makro ve mikro besin stratejileri."),
                    ("Fahrenheit 451", "Kitapların itfaiyeciler tarafından yakıldığı, televizyonun toplumu uyuşturduğu bir distopya."),
                    ("Taht Oyunları", "Yedi krallığın demir tahtı ele geçirmek için kurguladığı politik entrikalar ve fantastik savaşlar."),
                    ("Mülksüzler", "İki farklı gezegende yaşayan anarşist ve kapitalist toplumların felsefi karşılaştırması."),
                    ("Yüzyıllık Yalnızlık", "Büyülü gerçekçilik akımının başyapıtı olan, Buendia ailesinin yedi nesil süren trajik hikayesi."),
                    ("Bülbülü Öldürmek", "1930'ların Amerika'sında ırkçılık ve adaletsizlik konularını küçük bir kızın gözünden anlatan klasik."),
                    ("Çavdar Tarlasında Çocuklar", "Ergenlik sancıları çeken bir gencin, yetişkinlerin sahte dünyasına duyduğu isyan ve yabancılaşma."),
                    ("Sineklerin Tanrısı", "Issız bir adaya düşen çocukların, medeniyetten uzaklaştıkça içlerindeki vahşetin ortaya çıkması."),
                    ("Karamazov Kardeşler", "Bir baba cinayeti etrafında şekillenen, inanç, ahlak ve özgür irade üzerine derin felsefi tartışmalar."),
                    ("Hızlı ve Yavaş Düşünme", "İnsan beyninin sezgisel ve analitik iki farklı karar verme mekanizmasının psikolojik incelemesi."),
                    ("Tüfek, Mikrop ve Çelik", "İnsanlık tarihinde bazı toplumların neden diğerlerine göre daha hızlı geliştiğini inceleyen antropolojik eser."),
                    ("Soluk Mavi Nokta", "Uzayın derinliklerinden dünyamıza bakarak insanlığın evrendeki yerini sorgulayan astronomi kitabı."),
                    ("Aylak Adam", "Büyük şehirde modern hayatın tekdüzeliğinden kaçan ve gerçek sevgiyi arayan bir aydının psikolojisi."),
                    ("Çalıkuşu", "İdealist bir genç kadın öğretmenin, Anadolu'nun zorlu şartlarında verdiği eğitim ve yaşam mücadelesi."),
                    ("Siddhartha", "Hindistan'da ruhani bir uyanış ve aydınlanma arayışıyla yollara düşen bir gencin içsel yolculuğu."),
                    ("Vadideki Zambak", "Fransız taşrasında yaşanan, saf ve ulaşılmaz bir aşka duyulan derin melankoli ve tutku."),
                    ("Ölü Canlar", "Rusya'da köle statüsündeki ölü köylüleri kağıt üzerinde satın alarak zengin olmaya çalışan bir dolandırıcının hikayesi."),
                    ("Madame Bovary", "Taşra hayatının sıkıcılığından kurtulmak için lüks ve romantizm peşinde koşan bir kadının trajedisi."),
                    ("Uğultulu Tepeler", "İngiltere'nin kasvetli kırlarında iki aile arasında nesiller boyu süren yıkıcı bir intikam ve aşk."),
                    ("Gen Bencildir", "Evrimin birey veya tür düzeyinde değil, genlerin hayatta kalma mücadelesi üzerinden işlediğini savunan biyoloji kitabı."),
                    ("İknanın Psikolojisi", "İnsanların karar verme süreçlerini etkileyen ve evet demelerini sağlayan psikolojik tetikleyiciler."),
                    ("Kinesiyoloji Temelleri", "İnsan hareketlerinin mekaniği ve ağırlık kaldırırken eklemlere binen yüklerin analizi."),
                    ("İçten Yanmalı Motorlar Analizi", "Geleneksel otomobillerde silindir hacmi, tork üretimi ve yakıt verimliliği üzerine mühendislik prensipleri."),
                    ("Dağıtık Sistemler", "Birden fazla sunucunun tek bir makine gibi çalıştığı, büyük ölçekli ve yüksek erişilebilir mimariler."),
                    ("Siber Güvenlik ve Kriptografi", "Ağ üzerindeki verilerin şifrelenmesi ve kötü niyetli saldırılara karşı korunma yöntemleri."),
                    ("Harry Potter ve Felsefe Taşı", "Büyücülük okuluna kabul edilen yetim bir çocuğun, karanlık bir büyücüye karşı kaderiyle yüzleşmesi.")
                ]
                
                progress_bar = st.progress(0)
                status_text = st.empty()
                total_books = len(kitaplar)
                
                for i, (isim, aciklama) in enumerate(kitaplar):
                    status_text.text(f"Yapay Zeka İşliyor ({i+1}/{total_books}): {isim}")
                    vektor_str = str(model.encode(aciklama).tolist())
                    cursor.execute("INSERT INTO books (title, description, embedding) VALUES (:1, :2, TO_VECTOR(:3))", [isim, aciklama, vektor_str])
                    progress_bar.progress((i + 1) / total_books)
                
                conn.commit()
                cursor.close()
                conn.close()
                
                status_text.text("Bütün veriler başarıyla yüklendi!")
                st.success("✅ Şov Başlayabilir! 70 farklı kayıt vektörleriyle birlikte veritabanına işlendi.")
            except Exception as e:
                st.error(f"Veri yükleme hatası: {e}")